export const PSELECT_TYPE_FLIGHT = 'PSELECT_TYPE_FLIGHT'
export const PSELECT_TYPE_PASSENGER = 'PSELECT_TYPE_PASSENGER'
export const PSELECT_TYPE_BUTTON = 'PSELECT_TYPE_BUTTON'


export const MAIN_BLOCK = 'MAIN_BLOCK'
export const OPERATION_BLOCK = 'OPERATION_BLOCK'
export const FLIGHTSWITCH_BLOCK = 'FLIGHTSWITCH_BLOCK'
export const PSELECT_BLOCK = 'PSELECT_BLOCK'
export const TOPMENU_BLOCK = 'TOPMENU_BLOCK'

export const CMD_INPUT = 'cmdInput'

export const PREV_BTN_KEY = 'PREV_BTN_KEY'
export const NEXT_BTN_KEY = 'NEXT_BTN_KEY'
export const FLIGHTADD_BTN_KEY = 'FLIGHTADD_BTN_KEY'


export const PAGE_PASSENGER_LIST = 'PAGE_PASSENGER_LIST'
export const PAGE_ADD_PASSENGER = 'PAGE_ADD_PASSENGER'
export const PAGE_MODIFY_PHONE = 'PAGE_MODIFY_PHONE'
export const PAGE_STOP_PASSENGER = 'PAGE_STOP_PASSENGER'


export const SUBMIT_BTN_KEY = 'SUBMIT_BTN_KEY'

export const PADD_CN_KEY = 'PADD_CN_KEY'
export const PADD_SEX1_KEY = 'PADD_SEX1_KEY'
export const PADD_SEX2_KEY = 'PADD_SEX2_KEY'
export const PADD_SEX3_KEY = 'PADD_SEX3_KEY'
export const PADD_DN_KEY = 'PADD_DN_KEY'
export const PADD_ETI_KEY = 'PADD_ETI_KEY'

export const MPHONE_TE_KEY = 'MPHONE_TE_KEY'

export const PSTOP_NOTE_KEY = 'PSTOP_NOTE_KEY'
