export const PSELECT_TYPE_FLIGHT = 'PSELECT_TYPE_FLIGHT'
export const PSELECT_TYPE_PASSENGER = 'PSELECT_TYPE_PASSENGER'
export const PSELECT_TYPE_BUTTON = 'PSELECT_TYPE_BUTTON'


export const MAIN_BLOCK = 'MAIN_BLOCK'
export const OPERATION_BLOCK = 'OPERATION_BLOCK'
export const FLIGHTSWITCH_BLOCK = 'FLIGHTSWITCH_BLOCK'
export const PSELECT_BLOCK = 'PSELECT_BLOCK'
export const TOPMENU_BLOCK = 'TOPMENU_BLOCK'

export const CMD_INPUT = 'cmdInput'

export const PREV_BTN_KEY = 'PREV_BTN_KEY'
export const NEXT_BTN_KEY = 'NEXT_BTN_KEY'
export const FLIGHTADD_BTN_KEY = 'FLIGHTADD_BTN_KEY'
